### ISSUE TITLE
v14 support

### ISSUE THREAD

**Issue by devrimgunduz** [EnterpriseDB/pldebugger#1]
Hi,

pldebugger fails to build against v14. I see that you committed a fix for v14 already. This is a placeholder ticket for a new release, so that we can work on packaging.

Thanks! Devrim

**Comment by devrimgunduz-edb** [comment]
@dpage ping.

**Comment by dpage-edb** [comment]
https://github.com/EnterpriseDB/pldebugger/releases/tag/v1.4
