### ISSUE TITLE
Installing debugger in postgres:15 docker

### ISSUE THREAD

**Issue by ukolovda** [EnterpriseDB/pldebugger#11]
I use Docker-version postgres:15
But when try this line in Dockerfile
```
RUN apt-get install postgresql-15-pldebugger
```
It say 
```
E: Unable to locate package postgresql-15-pldebugger
The command '/bin/sh -c apt-get install postgresql-15-pldebugger' returned a non-zero code: 100
```

In postgres:14 this command (with version 14) worked fine.
I guess, there is no Debian package for pldebugger. Please, append it.

Thank you!

**Comment by dpage** [comment]
We don't maintain the packages for the debugger. Debian/Ubuntu packages are built by the PostgreSQL APT team; please see https://wiki.postgresql.org/wiki/Apt
