### ISSUE TITLE
Unclear README installation step

### ISSUE THREAD

**Issue by jflambert** [EnterpriseDB/pldebugger#15]
I'm trying to build from source and I'm stumped at the first step:

`Copy this directory to contrib/ in your PostgreSQL source tree.`

How exactly does one obtain this PostgreSQL source tree?

I'm using alpine 3.17.

**Comment by jflambert** [comment]
I ended up using `USE_PGXS=1 make` and `USE_PGXS=1 make install` instead of cloning the postgres source

**Comment by diraneyya** [comment]
Hello. We really need to improve the documentation here. I assigned this to myself.
