### ISSUE TITLE
The version of pldebugger

### ISSUE THREAD

**Issue by iriswind** [EnterpriseDB/pldebugger#17]
Hello, i install pldebugger(1.5 release) and the version of the extension in the database is displayed 1.1
Are release version and extension version the same thing?

**Comment by selfimmersion** [comment]
Actual. I have similar problem.

**Comment by selfimmersion** [comment]
![image](https://github.com/EnterpriseDB/pldebugger/assets/120722244/1f5c8cd7-767f-4b64-9f37-9576143c3181)

**Comment by dpage** [comment]
1.1 is the API version. 1.5 is the code version.

**Comment by selfimmersion** [comment]
Thanks a lot
