### ISSUE TITLE
Build failure against PG 17 Beta1

### ISSUE THREAD

**Issue by sandeep-edb** [EnterpriseDB/pldebugger#25]
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Werror=unguarded-availability-new -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -g -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -mmacosx-version-min=10.15 -arch x86_64 -arch arm64 -O2  -fvisibility=hidden -I. -I. -I../../src/include -I/opt/local/Current_v15/include -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk  -I/opt/local/20220418/include/libxml2 -I/opt/local/Current_v15/include -I/opt/local/Current_v15/include  -I/opt/local/Current_v15/include/libxml2 -I/opt/local/Current_v15/include -I/opt/local/Current_v15/include/openssl/  -c -o pldbgapi.o pldbgapi.c

dbgcomm.c:28:10: fatal error: 'storage/backendid.h' file not found
#include "storage/backendid.h"
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [dbgcomm.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from plugin_debugger.c:47:
./dbgcomm.h:23:38: error: unknown type name 'BackendId'
extern int dbgcomm_connect_to_target(BackendId targetBackend);
                                     ^
1 error generated.
make: *** [plugin_debugger.o] Error 1
plpgsql_debugger.c:1127:3: error: implicit declaration of function 'SPI_restore_connection' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                SPI_restore_connection();
                ^
plpgsql_debugger.c:1143:3: error: implicit declaration of function 'SPI_restore_connection' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                SPI_restore_connection();
                ^
plpgsql_debugger.c:1185:4: error: implicit declaration of function 'SPI_restore_connection' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        SPI_restore_connection();
                        ^
plpgsql_debugger.c:1200:4: error: implicit declaration of function 'SPI_restore_connection' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        SPI_restore_connection();
                        ^
4 errors generated.
make: *** [plpgsql_debugger.o] Error 1
In file included from pldbgapi.c:112:
./dbgcomm.h:23:38: error: unknown type name 'BackendId'
extern int dbgcomm_connect_to_target(BackendId targetBackend);
                                     ^
1 error generated.
make: *** [pldbgapi.o] Error 1

**Comment by dpage** [comment]
This is resolved with 0937f06b17cb694469a023ab28f16431f7a2ff6d
