### ISSUE TITLE
README.pldebugger missing

### ISSUE THREAD

**Issue by df7cb** [EnterpriseDB/pldebugger#27]
The Makefile still references the README.pldebugger file that was renamed to README.md:

```
/usr/bin/install -c -m 644 /home/myon/postgresql/pldebugger/pldebugger/README.pldebugger '/home/myon/postgresql/pldebugger/pldebugger/debian/postgresql-16-pldebugger/usr/share/doc/postgresql-doc-16/extension/'
/usr/bin/install: der Aufruf von stat für '/home/myon/postgresql/pldebugger/pldebugger/README.pldebugger' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
```

Please don't install README.md into the PG documentation directory, the generic name will conflict with other extensions doing the same mistake:
https://github.com/darold/pgtt/pull/51
https://github.com/segasai/q3c/pull/37

Instead, create a symlink README.pldebugger -> README.md and have the Makefile install that.

**Comment by dpage** [comment]
Argh, sorry about that. It should be OK now (I created a 1.7 release/tag).

Thanks.

**Comment by df7cb** [comment]
Thanks!
