### ISSUE TITLE
V13 support

### ISSUE THREAD

**Issue by mlwacomos** [EnterpriseDB/pldebugger#3]
Hi there. It does not fit version 13 of postgresql.

Is there anywhere an extension that can be used with posgre 13 / centos 7.8

thank you

**Comment by dpage** [comment]
pl/debugger supports PostgreSQL 13, and has since it (PG13) was released.

What makes you think it does not?

**Comment by hotsmile** [comment]
but i can't make it in  postgre13/centos8, 
first i found pg_config  get wrong PGXS, i change it ,but 
make USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I/usr/pgsql-13/lib/pgxs/src/makefiles/../../src/pl/plpgsql/src -I. -I./ -I/usr/include/pgsql/server -I/usr/include/pgsql/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o plpgsql_debugger.o plpgsql_debugger.c
plpgsql_debugger.c:12:10: 致命错误：postgres.h：没有那个文件或目录
 #include "postgres.h"

**Comment by dpage-edb** [comment]
Sorry for the long delay in replying - I missed the notification and if fell off the radar.

Please ensure you have the correct pg_config in your path, and if it still picks up the wrong PGXS data, it would be a packaging issue with your PostgreSQL distribution I believe. pldebugger gets all it's config info via PGXS (unless you do an in-tree build in the $PGSRC/contrib directory).
