### ISSUE TITLE
v15 suport

### ISSUE THREAD

**Issue by RekGRpth** [EnterpriseDB/pldebugger#8]
could You add v15 support like this https://github.com/powa-team/pg_stat_kcache/commit/1f9fb67813f608a31109b79aeb8d10c203f8ea7c ?

**Comment by ukolovda** [comment]
Additional info: https://sql-info.de/postgresql/notes/pg-fini-recent-changes-in-shared-library-coding.html

**Comment by dpage-edb** [comment]
This is fixed in 87a34870c8242541ac7b2930a92d59b5e8cd6dd6. Thanks!
